#!/bin/bash -x

ROOT=$HOME/workspace/kfritzbox
TARGET=$1

cd $ROOT

case "$TARGET" in
  cmake)
    mkdir -p build
    cd build
    cmake ..
  ;;
  all)
    cd build
    make 
  ;;
  clean)
    rm -rf build
  ;;  
  deb)
    dpkg-buildpackage
  ;;
  deb-install)
    sudo dpkg -i ../kfritzbox_0.1-1_i386.deb

esac
