######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 2 12:08:15 2008
######################################################################

CONFIG += qtestlib

# Input
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /usr/include/qt4/

# Input
HEADERS += ThreadTest.h
SOURCES += ThreadTest.cpp ../PThread++.cpp


