######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 2 12:08:15 2008
######################################################################

CONFIG += qtestlib
CONFIG += debug

# Input
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /usr/include/qt4/
INCLUDEPATH += ..
INCLUDEPATH += ../../libpthread++/
INCLUDEPATH += ../../libtcpclient++/
INCLUDEPATH += ../../libtcpclient++/test

# Input
HEADERS += ../../libtcpclient++/test/TcpSendFile.h
SOURCES += FritzTest.cpp ../../libtcpclient++/test/TcpSendFile.cpp
LIBS    += ../libfritz++.a
LIBS    += ../../libtcpclient++/libtcpclient++.a
LIBS    += ../../libpthread++/libpthread++.a


