######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 2 12:08:15 2008
######################################################################

CONFIG += qtestlib

# Input
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /usr/include/qt4/
INCLUDEPATH += ..
INCLUDEPATH += ../../libpthread++/

# Input
HEADERS += TcpSendFile.h
SOURCES += TcpClientTest.cpp  TcpSendFile.cpp
LIBS    += ../libtcpclient++.a
LIBS    += ../../libpthread++/libpthread++.a


